name: Deploy to Production Environment

on:
  release:
    types: [published]

jobs:
  # Deploy server to Vercel
  deploy-vercel:
    name: Deploy Server to Vercel
    if: github.event.release.target_commitish == 'master'
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      DEPLOYMENT_PLATFORM: ${{ secrets.DEPLOYMENT_PLATFORM }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use NodeJS v22.14.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install Vercel CLI
        run: npm install --global vercel@47.0.6

      - name: Build API docs
        run: |
          cd server
          npm install
          npm run build

      - name: Pull Vercel Environment Information
        run: |
          cd server
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          cd server
          chmod u+x ./scripts/buildVercel.sh
          chmod u+x ./scripts/replace.sh
          ./scripts/replace.sh
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          ./scripts/buildVercel.sh

      - name: Deploy Project Artifacts to Vercel
        run: |
          cd server
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Post Deployment Clean-up
        run: |
          cd server
          rm -r -f .vercel

  # Push development image to Docker Hub
  docker-build-push:
    name: Push Development Image
    if: github.event.release.target_commitish == 'master' && vars.DOCKERHUB_USERNAME != ''
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build Image
        run: |
          cp server/.env.example server/.env
          docker compose -f docker-compose.yml build

      - name: Push Image to Docker Hub
        run: docker compose -f docker-compose.yml push
